### ISSUE TITLE
Out of date code

### ISSUE THREAD

**Issue by DenysVisser** [electricimp/Wiznet_5500#15]
https://github.com/electricimp/Wiznet_5500/blob/8006751eb5c9d883c27768a8f77adeecff6af511/W5500.device.lib.nut#L654

Uses an out of date code:
https://developer.electricimp.com/api/imp/getmacaddress 

Change to "imp.net.info()"

**Comment by betzrhodes** [comment]
Fixed now released in v2.2.0
